DROP DATABASE IF EXISTS QL_FRESHER;
CREATE DATABASE QL_FRESHER;

USE QL_FRESHER;

-- EXERCISE 1

-- QUESTION 1
DROP TABLE IF EXISTS TRAINEE;
CREATE TABLE IF NOT EXISTS TRAINEE (
    TraineeID 			INT AUTO_INCREMENT PRIMARY KEY,
    Full_Name 			VARCHAR(50) NOT NULL,
    Birth_Date 			DATE NOT NULL,
    Gender 				ENUM('Male', 'Female','Unknown') DEFAULT ("Unknown"),
    ET_IQ 				TINYINT NOT NULL, CHECK(ET_IQ <= 20 AND ET_IQ >= 0),
    ET_Gmath 			TINYINT NOT NULL, CHECK(ET_Gmath <= 20 AND ET_Gmath >= 0),
    ET_English 			TINYINT NOT NULL, CHECK(ET_English <= 50 AND ET_English >= 0),
    Training_Class 		CHAR(5) NOT NULL,
    Evaluation_Note 	VARCHAR(255)
);

-- QUESTION 2
ALTER TABLE TRAINEE 
ADD COLUMN VTI_Account VARCHAR(30) UNIQUE KEY NOT NULL;

-- EXERCISE 2
DROP TABLE IF EXISTS TABLE_2;
CREATE TABLE IF NOT EXISTS TABLE_2 (
	ID				BIGINT AUTO_INCREMENT PRIMARY KEY,
    Name			VARCHAR(50) NOT NULL,
    Code			CHAR(5) NOT NULL,
    ModifiedDate	DATETIME
);

-- EXERCISE 3
DROP TABLE IF EXISTS TABLE_3;
CREATE TABLE IF NOT EXISTS TABLE_3 (
	ID				BIGINT AUTO_INCREMENT PRIMARY KEY,
    Name			VARCHAR(50) NOT NULL,
    BirthDate		DATE NOT NULL,
    Gender			ENUM("Male","Female","Unknown") DEFAULT ("Unknown"),
    isDeleteFlag	BOOLEAN DEFAULT 0
);
